[tasmota]
; Keep custom env behavior isolated
build_unflags               =
build_flags                 =

[env:tasmota32s3-bluetooth]
extends                     = env:tasmota32_base
board                       = esp32s3-qio_qspi
# board_upload.flash_size     = 16MB
# board_upload.maximum_size   = 16777216
# board_build.partitions      = partitions/esp32_partition_app3904k_fs11584k.csv
build_flags                 = ${env:tasmota32_base.build_flags}
                              -DFIRMWARE_BLUETOOTH
                              -DOTA_URL='""'
lib_extra_dirs              = lib/libesp32, lib/libesp32_div, lib/lib_basic, lib/lib_ssl, lib/lib_i2c
lib_ignore                  = Micro-RTSP
custom_files_upload         = ${env:tasmota32_base.custom_files_upload}
                              tasmota/berry/trelay/autoexec.be
                              tasmota/berry/trelay/trelay_ble_remote.be
